// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import "./libs/shim/expect.js";
import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';

export let options = { maxRedirects: 4,duration: '5m',vus: 20, };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    appurl: __ENV.appurl,
    contactid: randomIntBetween(1,20)
  }
});

export default function() {
  postman[Request]({
    name: "GetAllContacts",
    id: "275c5271-ce74-4b82-8832-55bdb3c4c1fb",
    method: "GET",
    address: "{{appurl}}/contacts"
  });

  postman[Request]({
    name: "SaveContact",
    id: "784d141a-82b1-4144-a3e9-8067c4b88a43",
    method: "POST",
    address: "{{appurl}}/contacts",
    data:
      '{"name":"shaik","email":"shaik@gmail.com","phone":5678952,"isFavorite":false}'
  });

  postman[Request]({
    name: "GetContactById",
    id: "e5d747ab-62de-4111-9962-e307a4d837db",
    method: "GET",
    address: "{{appurl}}/contacts/{{contactid}}"
  });

  postman[Request]({
    name: "UpdateContact",
    id: "69686a47-5410-488c-bae5-c6ba24cc59ba",
    method: "PUT",
    address: "{{appurl}}/contacts/{{contactid}}",
    data:
      '{"name":"shaik","email":"shaik@gmail.com","phone":5678952,"isFavorite":true}'
  });

  postman[Request]({
    name: "DeleteContact",
    id: "2a3eef14-0e89-4e9f-a28b-4f5aecb8e578",
    method: "DELETE",
    address: "{{appurl}}/contacts/{{contactid}}"
  });
}
